## python with data analysis :
#### Numpy-numerical python-->it is written in 'C' Lnaguage
* numpy arrays are faster compared to native lists
#### arrays can be Multidimentional arrays:
* we can work with tabula data as well as image data using multidimentional arrays.

* numpy arrays are homogenious in nature,np.arrays.


In [2]:
import numpy as np# by default it will be in jupiter 

In [6]:
a=np.array([1,2,3])
print(a,type(a),id(a),sep='\n')

[1 2 3]
<class 'numpy.ndarray'>
1924735813360


In [9]:
a[2]

3

In [10]:
len(a)

3

In [11]:
print(a.shape,a.size,a.ndim,sep='\n')

(3,)
3
1


In [12]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__o

In [16]:
a=np.array([1,'two',3.3,4+4j])
a
print(a,type(a),id(a),a.dtype,sep='\n')

['1' 'two' '3.3' '(4+4j)']
<class 'numpy.ndarray'>
1924736114704
<U64


In [17]:
type(a[0])

numpy.str_

In [18]:
b=np.array([1,2,3])
print(b,type(b),id(b),b.dtype,sep='\n')

[1 2 3]
<class 'numpy.ndarray'>
1924715843280
int32


In [19]:
c=np.array(range(1,10))
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
c[0],c[-1],c[::2],c[::-2]

(1, 9, array([1, 3, 5, 7, 9]), array([9, 7, 5, 3, 1]))

In [26]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [27]:
A=range(1,20,2)

In [28]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
z=np.array([[1,2,3],[4,5,6],[7,8,9]])
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
print(z.shape,z.size,z.ndim,len(z),sep='\n')

(3, 3)
9
2
3


In [33]:
np.arange(1,28).reshape(3,3,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [34]:
np.arange(1,21).reshape(2,2,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [48]:
h=np.arange(1,10).reshape(3,3)
h

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
h[0]

array([1, 2, 3])

In [50]:
z[0][0]

1

In [53]:
z[1,1]#INDEX rows by column

5

In [40]:
x=np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
x[0]

1

In [56]:
s=np.arange(1,28).reshape(3,3,3)
s


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [60]:
s[1,0,1]#0TH,1TH,2TH

11

In [63]:
s[2,1,0]

22

In [71]:
x=np.arange(1,37).reshape(2,6,3)#3d numpy array
print(x,x.shape,x.ndim,x.size,sep='\n')

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]
(2, 6, 3)
3
36


In [76]:
x=np.arange(1,37).reshape(2,2,3,3)#4 dimention 
print(x)

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]]

  [[10 11 12]
   [13 14 15]
   [16 17 18]]]


 [[[19 20 21]
   [22 23 24]
   [25 26 27]]

  [[28 29 30]
   [31 32 33]
   [34 35 36]]]]


In [75]:
x[1,0,1,1]

23

In [77]:
x[0,0,0,1],[]

2

In [78]:
h=np.arange(1,10).reshape(3,3)
h

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
h[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
h[0,:]#slicing columns

array([1, 2, 3])

In [82]:
h[0]

array([1, 2, 3])

In [84]:
h[0,::2]#slicing using two steps

array([1, 3])

In [85]:
h[0,::-2]#colums,start:end:stepsize

array([3, 1])

In [87]:
x[0,::-2]

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [88]:
x[::-2,::-2]

array([[[[28, 29, 30],
         [31, 32, 33],
         [34, 35, 36]]]])

In [89]:
h[:,::-2]

array([[3, 1],
       [6, 4],
       [9, 7]])

In [90]:
h

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
v=np.arange(1,126).reshape(5,5,5)
print(v)

[[[  1   2   3   4   5]
  [  6   7   8   9  10]
  [ 11  12  13  14  15]
  [ 16  17  18  19  20]
  [ 21  22  23  24  25]]

 [[ 26  27  28  29  30]
  [ 31  32  33  34  35]
  [ 36  37  38  39  40]
  [ 41  42  43  44  45]
  [ 46  47  48  49  50]]

 [[ 51  52  53  54  55]
  [ 56  57  58  59  60]
  [ 61  62  63  64  65]
  [ 66  67  68  69  70]
  [ 71  72  73  74  75]]

 [[ 76  77  78  79  80]
  [ 81  82  83  84  85]
  [ 86  87  88  89  90]
  [ 91  92  93  94  95]
  [ 96  97  98  99 100]]

 [[101 102 103 104 105]
  [106 107 108 109 110]
  [111 112 113 114 115]
  [116 117 118 119 120]
  [121 122 123 124 125]]]


In [95]:
v[:,::-2,:]

array([[[ 21,  22,  23,  24,  25],
        [ 11,  12,  13,  14,  15],
        [  1,   2,   3,   4,   5]],

       [[ 46,  47,  48,  49,  50],
        [ 36,  37,  38,  39,  40],
        [ 26,  27,  28,  29,  30]],

       [[ 71,  72,  73,  74,  75],
        [ 61,  62,  63,  64,  65],
        [ 51,  52,  53,  54,  55]],

       [[ 96,  97,  98,  99, 100],
        [ 86,  87,  88,  89,  90],
        [ 76,  77,  78,  79,  80]],

       [[121, 122, 123, 124, 125],
        [111, 112, 113, 114, 115],
        [101, 102, 103, 104, 105]]])

In [100]:
s=v[:,::-2]
print(s)

[[[ 21  22  23  24  25]
  [ 11  12  13  14  15]
  [  1   2   3   4   5]]

 [[ 46  47  48  49  50]
  [ 36  37  38  39  40]
  [ 26  27  28  29  30]]

 [[ 71  72  73  74  75]
  [ 61  62  63  64  65]
  [ 51  52  53  54  55]]

 [[ 96  97  98  99 100]
  [ 86  87  88  89  90]
  [ 76  77  78  79  80]]

 [[121 122 123 124 125]
  [111 112 113 114 115]
  [101 102 103 104 105]]]


In [158]:
v[:,::-2,::2]

array([[[ 21,  23,  25],
        [ 11,  13,  15],
        [  1,   3,   5]],

       [[ 46,  48,  50],
        [ 36,  38,  40],
        [ 26,  28,  30]],

       [[ 71,  73,  75],
        [ 61,  63,  65],
        [ 51,  53,  55]],

       [[ 96,  98, 100],
        [ 86,  88,  90],
        [ 76,  78,  80]],

       [[121, 123, 125],
        [111, 113, 115],
        [101, 103, 105]]])

In [139]:
v[0::2,0::2,0::2]

array([[[  1,   3,   5],
        [ 11,  13,  15],
        [ 21,  23,  25]],

       [[ 51,  53,  55],
        [ 61,  63,  65],
        [ 71,  73,  75]],

       [[101, 103, 105],
        [111, 113, 115],
        [121, 123, 125]]])

In [119]:
v.shape

(5, 5, 5)

In [128]:
v[0::2]

array([[[  1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25]],

       [[ 51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75]],

       [[101, 102, 103, 104, 105],
        [106, 107, 108, 109, 110],
        [111, 112, 113, 114, 115],
        [116, 117, 118, 119, 120],
        [121, 122, 123, 124, 125]]])

In [145]:
v[::-2,0::2,0::2]

array([[[101, 103, 105],
        [111, 113, 115],
        [121, 123, 125]],

       [[ 51,  53,  55],
        [ 61,  63,  65],
        [ 71,  73,  75]],

       [[  1,   3,   5],
        [ 11,  13,  15],
        [ 21,  23,  25]]])

In [159]:
v[::-2,::3,::-1]

array([[[105, 104, 103, 102, 101],
        [120, 119, 118, 117, 116]],

       [[ 55,  54,  53,  52,  51],
        [ 70,  69,  68,  67,  66]],

       [[  5,   4,   3,   2,   1],
        [ 20,  19,  18,  17,  16]]])

In [160]:
def foo (x):
    return x**2

In [167]:
alist,anparray=list(range(1,6)),np.arange(1,6)

In [168]:
foo(anparray)

array([ 1,  4,  9, 16, 25])

In [172]:
import time 
from time import time

In [173]:
s=time()
x=[i for i in range(200000)]
e=time()
print(e-s)

0.00793004035949707


In [174]:
s=time()
x=np.arange(200000)
e=time()
print(e-s)

0.0019931793212890625


In [220]:
def sam(x):
    return x**x

In [221]:
alist,array=list(range(1,6)),np.arange(1,6)

In [222]:
sam(array)

array([   1,    4,   27,  256, 3125])

In [215]:
np.eye(5,5)#identity matrix,diognal (explore and understand identity matrix and code the same)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [190]:
np.zeros(5)#explore it and code it

array([0., 0., 0., 0., 0.])

In [223]:
np.ones(5,dtype=int)#explore it and code it

array([1, 1, 1, 1, 1])