# Problem-Solving with NumPy


1. Write a function, foo_1, that takes a NumPy array `arr` and returns the indices of the elements that are closest to a given target. If target is not in the given array, it should return ‘no item found’

In [18]:
import numpy as np

def foo_1(arr, target):
    if target not in arr: 
        return 'no item found'
    indices = [i for i in range(len(arr)) if arr[i] == target]
    return indices
#my_element with [i for i in range(len(my_list)) if my_list[i] == my_element] 

* In the context of the foo_1 function, the 'target' is the value you want to find in the given NumPy array arr. The function is designed to return the indices of elements in the array that are closest to this target value.
* Target/Mean Encoding for Categorical Attributes ,Machine Learning ,Python. Mean encoding, also known as target encoding, is a technique used to encode categorical attributes in machine learning models using python. It involves replacing each category with the mean target value of the corresponding target variable.
* in the above code the target is used to find the indices of the elements given in the list to the near values of the targets .

In [19]:
arr = np.array([3,8,7,7,7,7,7,8,7,10])
target = 7
foo_1(arr, target)

[2, 3, 4, 5, 6, 8]

In [20]:
arr = np.array([3,8,7,7,7,7,7,8,7,10])
target = 11
foo_1(arr, target)

'no item found'

## test case_if we use 2d array

In [32]:
x=np.random.randint(1,7,(3,4))

In [33]:
x


array([[4, 2, 4, 5],
       [2, 2, 3, 6],
       [1, 1, 1, 1]])

In [37]:
target =2
foo_1(arr, target)

'no item found'

##### i think its not working with 2 dimenional array

##  test case_if we use strings in between

In [45]:
arr=np.array([3,8,'saniya',7,7,7,7,8,7,'sameera'])
arr


array(['3', '8', 'saniya', '7', '7', '7', '7', '8', '7', 'sameera'],
      dtype='<U11')

In [47]:
target = 7
foo_1(arr, target)

C:\Users\Sam\AppData\Local\Temp\ipykernel_5552\495981005.py:4: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if target not in arr:


'no item found'

##### its showing a warning if we use strings in between the array and its not giving output too

2. Write a user defined function foo_2 that takes a 1 or 2 dim NumPy array arr and returns a new n-1 dim array, where each element is replaced by the count of non-zero elements wrt axis.



In [84]:
import numpy as np

def foo_2(arr, axis=None):
    if arr.ndim == 1:
        return np.count_nonzero(arr)
    elif arr.ndim == 2:
        return np.sum(np.where(arr != 0, 1, 0), axis=axis)
    elif arr.ndim == 3:
        return np.sum(np.where(arr != 0, 1, 0), axis=axis)
    else:
        return 'Unsupported dimension'

In [100]:
arr = np.array([[1, 2, 3, 4],
                [0, 5, 0, 0],
                [2, 0, 1, 0]])
foo_2(arr, axis = 1)

array([4, 1, 2], dtype=int64)

In [101]:
foo_2(arr, axis = 0)

array([2, 2, 2, 1], dtype=int64)

In [117]:
#arr1 = np.array([[1, 2, 3, 4],
               # [0, 5, 0, 0],
                #[2, 0, 1, 0]],
#
 #               [[2, 0, 1, 0],
  #               [0, 5, 0, 0],
   #              [1, 2, 3, 4]])


#foo_2(arr1 , axis = 0)


In [103]:
foo_2(arr1 , axis = 1)

array([[2, 2, 2, 1],
       [2, 2, 2, 1]], dtype=int64)

In [112]:
foo_2(arr1 , axis = 1)

array([[2, 2, 2, 1],
       [2, 2, 2, 1]], dtype=int64)

In [114]:
foo_2(arr1 , axis = 2)

array([[4, 1, 2],
       [2, 1, 4]], dtype=int64)

3. You are given a 2D NumPy array of data representing student scores. Each row represents a student, and each column represents a subject. Extract the scores of all students who scored above 90 in at least one subject. Provide the resulting array.

In [80]:
data = np.array([[85, 89, 88], [78, 89, 94], [91, 87, 90], [87, 95, 84]])
indices = np.where(data > 90)
print("score of students who secured greater than 90:")
print(indices)
unique_row_indices = np.unique(indices[0])
result = data[unique_row_indices, :]
print("\nScores of students who scored above 90 in at least one subject:")
print(result)

score of students who secured greater than 90:
(array([1, 2, 3], dtype=int64), array([2, 0, 1], dtype=int64))

Scores of students who scored above 90 in at least one subject:
[[78 89 94]
 [91 87 90]
 [87 95 84]]


4. You are provided with a 2D NumPy array of data representing sales data for different products. Each row corresponds to a product, and each column represents the monthly sales for a specific month. Calculate the following statistics for each product: mean, median, standard deviation, and the month with the highest sales


In [107]:
data=np.array([[120,150,130,110],
              [200,180,220,250],
              [90,100,95,110],
              [300,280,320,340]])

In [118]:
meanofproduct = np.mean(data, axis=1)
medianofproduct = np.median(data, axis=1)
sdofproduct = np.std(data, axis=1)
max_month_per_product = np.argmax(data, axis=1)
for i in range(len(data)):
    print(f"Product {i + 1}:")
    print(f"  Mean: {meanofproduct[i]:.2f}")
    print(f"  Median: {medianofproduct[i]:.2f}")
    print(f"  Standard Deviation: {sdofproduct[i]:.2f}")
    print(f"  Month with the Highest Sales: Month {max_month_per_product[i] + 1}")
    print("\n")
#this is the best part of arrays it will perform element wise operations

Product 1:
  Mean: 127.50
  Median: 125.00
  Standard Deviation: 14.79
  Month with the Highest Sales: Month 2


Product 2:
  Mean: 212.50
  Median: 210.00
  Standard Deviation: 25.86
  Month with the Highest Sales: Month 4


Product 3:
  Mean: 98.75
  Median: 97.50
  Standard Deviation: 7.40
  Month with the Highest Sales: Month 4


Product 4:
  Mean: 310.00
  Median: 310.00
  Standard Deviation: 22.36
  Month with the Highest Sales: Month 4





5. Create a NumPy array of size 1000 with random integers between 1 and 100. Then, use NumPy functions to find the top 10 most frequently occurring values in the array.


In [119]:
z=np.random.randint(1,100,1000)

In [120]:
z

array([34, 54, 59, 83, 83, 23, 71, 71, 30, 97, 90, 66, 29, 13, 16, 96, 79,
        6, 93, 19,  8, 75, 22, 76, 39, 42, 30, 14, 21, 95, 84, 48,  6, 99,
       67,  1, 88, 56, 59, 34, 78, 93,  4, 23, 29, 43, 23, 23, 20, 55, 45,
       30, 73, 78, 73, 37,  5,  4, 59, 26, 99, 51, 17, 15, 31, 57, 87, 53,
       16, 33, 82, 40,  5, 34, 45, 66, 81, 36, 58, 60, 34, 30, 50, 98, 27,
       17,  6, 16, 44, 62, 24, 76, 86, 16, 31, 50, 29, 51,  2, 68,  5, 99,
       60, 26, 91, 67, 59, 47, 81, 95, 56, 53, 46, 78, 94, 54, 43, 94, 69,
       47, 68, 74, 47, 44, 69, 72, 29, 49, 22, 51,  1, 77, 74,  8, 64, 70,
       53, 77, 99, 22, 50, 84, 63, 42, 39, 83, 29, 38, 41,  1, 47, 92, 89,
       89, 97, 94, 63, 96, 53, 28, 51, 35, 32, 46, 30, 80, 62, 26, 42, 67,
        4, 70, 36, 41,  6, 29, 88, 30, 21, 98, 69, 97,  1, 76, 28, 30, 64,
       60, 62,  2, 13, 91, 46, 20, 97, 46, 63, 92, 85, 57, 46,  6, 53, 88,
       29, 24, 98, 59, 30, 93, 54, 20, 62,  8, 20,  9,  5, 81, 97, 57,  4,
       89, 63, 88, 33, 93

In [122]:
counts = np.bincount(z)

top_indices = np.argsort(-counts)[:10]

print("Top 10 most frequently occurring values:")
for index in top_indices:
    print(f"Value: {index}, Count: {counts[index]}")


Top 10 most frequently occurring values:
Value: 31, Count: 18
Value: 83, Count: 16
Value: 46, Count: 16
Value: 30, Count: 16
Value: 9, Count: 16
Value: 97, Count: 16
Value: 76, Count: 15
Value: 72, Count: 15
Value: 22, Count: 14
Value: 94, Count: 14


###### In this code, np.bincount(z) returns an array where the ith element represents the count of occurrences of the integer i in the array z

### numpy.bincount
* numpy.bincount(x, /, weights=None, minlength=0)
  Count number of occurrences of each value in array of non-negative ints.

* The number of bins (of size 1) is one larger than the largest value in x. If minlength is specified, there will be at least this number of bins in the output array (though it will be longer if necessary, depending on the contents of x). Each bin gives the number of occurrences of its index value in x. If weights is specified the input array is weighted by it, i.e. if a value n is found at position i, out[n] += weight[i] instead of out[n] += 1.